services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voting
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  backend:
    build: ./backend/VotingSystem.API
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend/voting-ui
    ports:
      - "5173:5173"
    depends_on:
      - backend
